---
# Note make download_tools and make openstack commands run
# in https://github.com/rdo-infra/review.rdoproject.org-config/blob/master/playbooks/crc/openstack.yaml
# We can override the openstack operator image by defining openstack_img in the zuul job

- hosts: "{{ target_host | default('controller') }}"
  name: Deploy Openstack Operators
  vars:
    nova_operator_basedir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/nova-operator"
  tasks:
    - name: Deploy OpenStack
      environment:
        KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
        PATH: "{{ cifmw_path | default(ansible_env.PATH) }}"
      ansible.builtin.command: "oc apply -k {{ nova_operator_basedir }}/ci/nova-operator-compute-kit/topology/ci"
      changed_when: true

    - name: Make sure Openstack CR is ready
      environment:
        KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
        PATH: "{{ cifmw_path | default(ansible_env.PATH) }}"
      ansible.builtin.command: oc wait OpenstackControlPlane openstack --for condition=Ready --timeout=180s
      changed_when: false
      retries: 3
      delay: 5
      register: status
      until: status.rc == 0
