---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-nova
  failurePolicy: Fail
  name: mnova-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nova
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novaapi
  failurePolicy: Fail
  name: mnovaapi-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novaapis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novacell
  failurePolicy: Fail
  name: mnovacell-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novacells
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novacompute
  failurePolicy: Fail
  name: mnovacompute-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novacomputes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novaconductor
  failurePolicy: Fail
  name: mnovaconductor-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novaconductors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novametadata
  failurePolicy: Fail
  name: mnovametadata-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novametadata
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novanovncproxy
  failurePolicy: Fail
  name: mnovanovncproxy-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novanovncproxies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nova-openstack-org-v1beta1-novascheduler
  failurePolicy: Fail
  name: mnovascheduler-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novaschedulers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-nova
  failurePolicy: Fail
  name: vnova-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nova
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novaapi
  failurePolicy: Fail
  name: vnovaapi-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novaapis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novacell
  failurePolicy: Fail
  name: vnovacell-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novacells
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novacompute
  failurePolicy: Fail
  name: vnovacompute-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novacomputes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novaconductor
  failurePolicy: Fail
  name: vnovaconductor-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novaconductors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novametadata
  failurePolicy: Fail
  name: vnovametadata-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novametadata
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novanovncproxy
  failurePolicy: Fail
  name: vnovanovncproxy-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novanovncproxies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nova-openstack-org-v1beta1-novascheduler
  failurePolicy: Fail
  name: vnovascheduler-v1beta1.kb.io
  rules:
  - apiGroups:
    - nova.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - novaschedulers
  sideEffects: None
