# This rule is not used by the project nova-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to nova.openstack.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nova-operator
    app.kubernetes.io/managed-by: kustomize
  name: novacompute-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novacomputes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novacomputes/status
  verbs:
  - get
