apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: novamigrationtargets.nova.openstack.org
spec:
  group: nova.openstack.org
  names:
    kind: NovaMigrationTarget
    listKind: NovaMigrationTargetList
    plural: novamigrationtargets
    singular: novamigrationtarget
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NovaMigrationTarget is the Schema for the novamigrationtargets
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NovaMigrationTargetSpec defines the desired state of NovaMigrationTarget
          properties:
            commonConfigMap:
              description: name of configmap which holds general information on the
                OSP env
              type: string
            novaComputeImage:
              description: container image to run for the daemon
              type: string
            roleName:
              description: Name of the worker role created for OSP computes
              type: string
            serviceAccount:
              description: service account used to create pods
              type: string
            sshdPort:
              description: SSHD port
              format: int32
              type: integer
          required:
          - commonConfigMap
          - novaComputeImage
          - roleName
          - serviceAccount
          - sshdPort
          type: object
        status:
          description: NovaMigrationTargetStatus defines the observed state of NovaMigrationTarget
          properties:
            count:
              description: Count is the number of nodes the daemon is deployed to
              format: int32
              type: integer
            daemonsetHash:
              description: Daemonset hash used to detect changes
              type: string
          required:
          - count
          - daemonsetHash
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
