apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iscsids.nova.openstack.org
spec:
  group: nova.openstack.org
  names:
    kind: Iscsid
    listKind: IscsidList
    plural: iscsids
    singular: iscsid
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            iscsidImage:
              description: Image is the Docker image to run for the daemon
              type: string
            label:
              description: Label is the value of the 'daemon=' label to set on a node
                that should run the daemon
              type: string
          required:
          - label
          - iscsidImage
          type: object
        status:
          properties:
            count:
              description: Count is the number of nodes the daemon is deployed to
              format: int32
              type: integer
            daemonsetHash:
              description: Daemonset hash used to detect changes
              type: string
          required:
          - count
          - daemonsetHash
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
