apiVersion: nova.openstack.org/v1beta1
kind: NovaMetadata
metadata:
  name: novametadata-sample
spec:
  apiDatabaseHostname: openstack
  apiMessageBusSecretName: rabbitmq-transport-url-nova-api-transport
  cellDatabaseHostname: openstack
  cellDatabaseUser: nova_cell0
  containerImage: quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
  apiDatabaseUser: nova_api
  serviceAccount: nova
  registeredCells: {}
