apiVersion: nova.openstack.org/v1beta1
kind: NovaCell
metadata:
  name: novacell0-sample
spec:
  # cell0 always needs API DB access
  apiDatabaseHostname: openstack
  cellDatabaseHostname: openstack
  cellMessageBusSecretName: rabbitmq-transport-url-nova-api-transport
  cellName: cell0
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
  serviceAccount: nova
