apiVersion: nova.openstack.org/v1beta1
kind: NovaAPI
metadata:
  name: novaapi-sample
spec:
  secret: osp-secret
  passwordSelectors:
    service: NovaPassword
    apiDatabase: NovaAPIDatabasePassword
    apiMessageBus: NovaAPIMessageBusPassword
    cellDatabase: NovaCell0DatabasePassword
    cellMessageBus: null
  serviceUser: nova
  keystoneAuthURL: http://keystone-internal-openstack.apps-crc.testing
  apiDatabaseUser: nova
  # This is the hostname of the default DB today
  apiDatabaseHostname: openstack
  apiMessageBusUser: nova
  # Q: do we need db an rabbit port? it seems today we use the default port
  # This is the hostname of the default Rabbit today
  apiMessageBusHostname: default-security-context
  customServiceConfig: |
    # service config customization
    debug=True
  defaultConfigOverwrite:
    policy.yaml: |
      # my custom policy
  containerImage: quay.io/tripleozedcentos9/openstack-nova-api:current-tripleo
  replicas: 1
  nodeSelector: {}
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.1
      memory: 200Mi
  debug:
    stopDBSync: False
    stopService: False
    preserveJob: False
