apiVersion: nova.openstack.org/v1beta1
kind: NovaAPI
metadata:
  name: novaapi-sample
spec:
  apiDatabaseHostname: openstack
  cell0DatabaseHostname: openstack
  containerImage: quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
  serviceAccount: nova
  registeredCells: {}
