apiVersion: nova.openstack.org/v1beta1
kind: NovaCell
metadata:
  name: novacell2-without-upcall-sample
spec:
  cellDatabaseHostname: openstack
  cellName: cell2
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
  serviceAccount: nova
