apiVersion: nova.openstack.org/v1beta1
kind: NovaConductor
metadata:
  name: novaconductor-sample
spec:
  cellName: cell1
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
  serviceAccount: nova
  memcachedInstance: memcached
